name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rustfmt
      run: cargo fmt -- --check
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Tests
      run: cargo test
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Build and Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ github.repository }}
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tags: latest
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DAD_BOD_HOST }}
        username: ${{ secrets.DAD_BOD_SSH_USERNAME }}
        key: ${{ secrets.DAD_BOD_SSH_KEY }}
        port: ${{ secrets.DAD_BOD_SSH_PORT }}
        script: |
          docker login https://ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
          docker stop $(docker ps -a | grep ${{ secrets.DAD_BOD_IMAGE_NAME }} | awk '{print $1}')
          docker rm ${{ secrets.DAD_BOD_IMAGE_NAME }}
          docker run -d --pull always -e DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} -e NASA_API_KEY=${{ secrets.NASA_API_KEY }} --name ${{ secrets.DAD_BOD_IMAGE_NAME }} ghcr.io/${{ github.repository }}:latest


